-- Schema canonica PostgreSQL pentru e-TVA Reconciliere (etva_testare / etva_productie).
-- IDEMPOTENT: se poate aplica oricand, pe o baza goala sau pe una existenta -
--   psql -d etva_testare -f etva/pg_schema.sql
-- Corespondentul PG al portal/db.py::_SCHEMA + etva/db.py::_SCHEMA, cu trei
-- diferente structurale deliberate (vezi planning/migrare-postgres.md):
--   1. Cele 7 tabele "per-firma" (in SQLite: cate un fisier SQLCipher separat
--      per firma) devin tabele partajate cu o coloana firm_id, izolate prin
--      Row-Level Security: politica `izolare_firma` filtreaza dupa
--      current_setting('app.firm_id') pe care adaptorul o seteaza per sesiune.
--   2. Coloanele boolean/timestamp/numeric folosesc tipurile reale PG
--      (etva/pg.py::EXPECTED_SCHEMA le verifica la pornire).
--   3. firm_keys NU are foreign key spre firms - randurile orfane sunt
--      pastrate intentionat la stergerea firmelor (cheia ramane recuperabila).
-- Verificarea de conformitate: etva/pg.py::verify_schema().

-- ============ tabele portal (partajate, fara RLS - master vede tot) ============

CREATE TABLE IF NOT EXISTS firms(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  cui text UNIQUE NOT NULL,
  tip text NOT NULL DEFAULT 'contabilitate',
  active boolean NOT NULL DEFAULT TRUE,
  email_verificat boolean NOT NULL DEFAULT FALSE,
  email_verificare_token text,
  creat_la timestamptz,
  trial_expira_la timestamptz,
  ciclu_facturare text,
  trial_reminder_ultim_prag integer,
  arhivata_la timestamptz,
  reconcilieri_lunare_estimate integer);
-- Bazele create inainte de coloana de mai sus se aduc la zi aici (no-op pe
-- bazele deja corecte) - acelasi pattern ca la contracts.
ALTER TABLE firms ADD COLUMN IF NOT EXISTS reconcilieri_lunare_estimate integer;

CREATE TABLE IF NOT EXISTS users(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text UNIQUE NOT NULL,
  pw_hash text NOT NULL,
  email text,
  is_master boolean NOT NULL DEFAULT FALSE,
  onboarding_completat boolean NOT NULL DEFAULT FALSE,
  active boolean NOT NULL DEFAULT TRUE);

CREATE TABLE IF NOT EXISTS user_firms(
  user_id integer NOT NULL REFERENCES users(id),
  firm_id integer NOT NULL REFERENCES firms(id),
  role text NOT NULL,
  active boolean NOT NULL DEFAULT TRUE,
  PRIMARY KEY (user_id, firm_id));

CREATE TABLE IF NOT EXISTS firm_keys(
  firm_id integer PRIMARY KEY,
  wrapped_key bytea NOT NULL);
-- Fara FK spre firms, nici in SQLite: randurile orfane sunt politica
-- deliberata (cheia ramane recuperabila dupa stergerea administrativa a
-- firmei), iar datele reale contin deja astfel de orfani.
ALTER TABLE firm_keys DROP CONSTRAINT IF EXISTS firm_keys_firm_id_fkey;

CREATE TABLE IF NOT EXISTS pipeline_log(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_env text NOT NULL,
  target_env text NOT NULL,
  commit_hash text NOT NULL,
  promoted_by text NOT NULL,
  promoted_at timestamptz NOT NULL);

CREATE TABLE IF NOT EXISTS announcements(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesaj text NOT NULL,
  tip text NOT NULL DEFAULT 'informativ',
  incepe_la timestamptz NOT NULL,
  se_termina_la timestamptz NOT NULL,
  creat_de text NOT NULL,
  creat_la timestamptz NOT NULL,
  activ boolean NOT NULL DEFAULT TRUE);

CREATE TABLE IF NOT EXISTS contact_messages(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nume text NOT NULL,
  email text NOT NULL,
  tip text NOT NULL DEFAULT 'general',
  mesaj text NOT NULL,
  trimis_de text,
  firma text,
  creat_la timestamptz NOT NULL,
  citit boolean NOT NULL DEFAULT FALSE);

CREATE TABLE IF NOT EXISTS master_actions(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actiune text NOT NULL,
  detalii text,
  creat_de text NOT NULL,
  creat_la timestamptz NOT NULL);

CREATE TABLE IF NOT EXISTS deletion_requests(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  username text NOT NULL,
  firm_id integer,
  firm_name text,
  creat_la timestamptz NOT NULL,
  termen_la timestamptz NOT NULL,
  stare text NOT NULL DEFAULT 'in_asteptare',
  procesat_la timestamptz,
  procesat_de text);
-- deletion_requests.firm_id e informativ (numele firmei e oricum pastrat ca
-- text) - fara FK, la fel ca in schema SQLite.
ALTER TABLE deletion_requests DROP CONSTRAINT IF EXISTS deletion_requests_firm_id_fkey;

CREATE TABLE IF NOT EXISTS anaf_oauth_tokens(
  firm_id integer PRIMARY KEY REFERENCES firms(id),
  wrapped_access_token bytea NOT NULL,
  wrapped_refresh_token bytea NOT NULL,
  obtinut_la timestamptz NOT NULL,
  expira_la timestamptz NOT NULL,
  autorizat_de text NOT NULL);

CREATE TABLE IF NOT EXISTS invoices(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serie text NOT NULL,
  numar integer NOT NULL,
  firm_id integer NOT NULL REFERENCES firms(id),
  firm_name text NOT NULL,
  firm_cui text NOT NULL,
  descriere text NOT NULL,
  perioada_inceput timestamptz,
  perioada_sfarsit timestamptz,
  data_emiterii timestamptz NOT NULL,
  data_scadentei timestamptz,
  valoare_neta numeric NOT NULL,
  cota_tva numeric NOT NULL DEFAULT 21,
  valoare_tva numeric NOT NULL,
  valoare_totala numeric NOT NULL,
  moneda text NOT NULL DEFAULT 'RON',
  stare text NOT NULL DEFAULT 'emisa',
  creat_de text NOT NULL,
  creat_la timestamptz NOT NULL,
  anaf_index_incarcare text,
  anaf_stare text NOT NULL DEFAULT 'netrimisa',
  anaf_id_descarcare text,
  anaf_raspuns bytea,
  anaf_trimis_la timestamptz,
  UNIQUE(serie, numar));

CREATE TABLE IF NOT EXISTS payments(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firm_id integer NOT NULL REFERENCES firms(id),
  ciclu_facturare text NOT NULL,
  suma numeric NOT NULL,
  moneda text NOT NULL DEFAULT 'RON',
  recurent boolean NOT NULL DEFAULT FALSE,
  stare text NOT NULL DEFAULT 'in_asteptare',
  creat_la timestamptz NOT NULL,
  validat_de text,
  validat_la timestamptz,
  invoice_id integer REFERENCES invoices(id));

CREATE TABLE IF NOT EXISTS planuri_facturare(
  tip text NOT NULL,
  ciclu_facturare text NOT NULL,
  pret_lunar_ron numeric NOT NULL,
  actualizat_de text,
  actualizat_la timestamptz,
  PRIMARY KEY (tip, ciclu_facturare));

CREATE TABLE IF NOT EXISTS contracts(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firm_id integer NOT NULL REFERENCES firms(id),
  numar integer NOT NULL UNIQUE,
  ciclu_facturare text NOT NULL,
  suma numeric NOT NULL,
  beneficiar_denumire text NOT NULL,
  beneficiar_cui text NOT NULL,
  beneficiar_adresa text NOT NULL,
  stare text NOT NULL DEFAULT 'in_asteptare',
  creat_la timestamptz NOT NULL,
  metoda_semnatura text,
  semnatura_mouse_img bytea,
  semnatura_verificata boolean NOT NULL DEFAULT FALSE,
  semnatura_detalii text,
  semnat_la timestamptz,
  reziliere_solicitata_la timestamptz,
  reziliat_la timestamptz,
  reziliat_de text,
  ramburs_procent numeric,
  esemneaza_request_id text,
  esemneaza_document_pdf bytea,
  esemneaza_certificate_pdf bytea,
  prestator_semnat_la timestamptz,
  contract_xml_final bytea);
-- Bazele create inainte ca aceste doua coloane sa existe se aduc la zi aici
-- (ADD COLUMN IF NOT EXISTS e no-op pe bazele deja corecte).
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS prestator_semnat_la timestamptz;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS contract_xml_final bytea;

CREATE TABLE IF NOT EXISTS login_lockouts(
  identificator text PRIMARY KEY,
  incercari integer NOT NULL DEFAULT 0,
  ultima_incercare timestamptz,
  blocat_pana timestamptz);

CREATE TABLE IF NOT EXISTS setari_tva(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cota_procent numeric NOT NULL,
  activa boolean NOT NULL DEFAULT FALSE,
  actualizat_de text,
  actualizat_la timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS idx_setari_tva_activa
  ON setari_tva(activa) WHERE activa;

-- Nomenclatorul "abonament standard + reconcilieri": un singur rand (id=1)
-- cu cate reconcilieri/luna include abonamentul standard al firmelor
-- directe, marimea unui pachet extra si pretul lui lunar - editabil din
-- /master/nomenclator (vezi portal/db.py::get/set_pachet_reconcilieri).
CREATE TABLE IF NOT EXISTS pachete_reconcilieri(
  id integer PRIMARY KEY CHECK (id = 1),
  reconcilieri_incluse integer NOT NULL,
  marime_pachet integer NOT NULL,
  pret_pachet_lunar_ron numeric NOT NULL,
  actualizat_de text,
  actualizat_la timestamptz);

-- ===== tabele per-firma (in SQLite: fisiere SQLCipher separate; aici RLS) =====
-- firm_id are DEFAULT current_setting('app.firm_id')::int ca INSERT-urile
-- existente din etva/* (care nu cunosc coloana) sa primeasca automat firma
-- sesiunii curente si sa treaca de WITH CHECK.

CREATE TABLE IF NOT EXISTS clients(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firm_id integer NOT NULL REFERENCES firms(id)
    DEFAULT current_setting('app.firm_id', true)::int,
  cui text NOT NULL,
  name text NOT NULL,
  gdpr_confirmat boolean NOT NULL DEFAULT FALSE,
  gdpr_confirmat_de text,
  gdpr_confirmat_la timestamptz);
-- Bazele create inainte de coloanele GDPR se aduc la zi aici (no-op pe
-- bazele deja corecte); clientii existenti raman 'neconfirmat' - starea
-- lor reala, nu una inventata.
ALTER TABLE clients ADD COLUMN IF NOT EXISTS gdpr_confirmat boolean NOT NULL DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS gdpr_confirmat_de text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS gdpr_confirmat_la timestamptz;
-- In SQLite UNIQUE(cui) era per-fisier, deci per-firma; pe tabela partajata
-- echivalentul corect e unicitatea pe (firm_id, cui) - doua firme de
-- contabilitate pot avea acelasi client.
ALTER TABLE clients DROP CONSTRAINT IF EXISTS clients_cui_key;
CREATE UNIQUE INDEX IF NOT EXISTS idx_clients_firm_cui ON clients(firm_id, cui);

CREATE TABLE IF NOT EXISTS client_assignments(
  firm_id integer NOT NULL REFERENCES firms(id)
    DEFAULT current_setting('app.firm_id', true)::int,
  username text NOT NULL,
  client_id integer NOT NULL,
  PRIMARY KEY (username, client_id));

CREATE TABLE IF NOT EXISTS reconciliations(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firm_id integer NOT NULL REFERENCES firms(id)
    DEFAULT current_setting('app.firm_id', true)::int,
  client_id integer,
  period text NOT NULL,
  created_at timestamptz NOT NULL,
  created_by text NOT NULL);

CREATE TABLE IF NOT EXISTS invoices_company(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firm_id integer NOT NULL REFERENCES firms(id)
    DEFAULT current_setting('app.firm_id', true)::int,
  reconciliation_id integer NOT NULL,
  partner_cui text,
  invoice_no text,
  date text,
  base numeric,
  vat numeric,
  category text);

CREATE TABLE IF NOT EXISTS invoices_anaf(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firm_id integer NOT NULL REFERENCES firms(id)
    DEFAULT current_setting('app.firm_id', true)::int,
  reconciliation_id integer NOT NULL,
  partner_cui text,
  invoice_no text,
  date text,
  base numeric,
  vat numeric,
  category text);

CREATE TABLE IF NOT EXISTS differences(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firm_id integer NOT NULL REFERENCES firms(id)
    DEFAULT current_setting('app.firm_id', true)::int,
  reconciliation_id integer NOT NULL,
  diff_type text NOT NULL,
  details text NOT NULL);

CREATE TABLE IF NOT EXISTS audit_log(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firm_id integer NOT NULL REFERENCES firms(id)
    DEFAULT current_setting('app.firm_id', true)::int,
  user_id text,
  action text NOT NULL,
  entity text,
  entity_id text,
  ts timestamptz NOT NULL);

-- Bazele create inaintea acestui fisier canonic nu au DEFAULT-ul pe firm_id -
-- SET DEFAULT e idempotent, il impunem explicit pe toate 7.
ALTER TABLE clients            ALTER COLUMN firm_id SET DEFAULT current_setting('app.firm_id', true)::int;
ALTER TABLE client_assignments ALTER COLUMN firm_id SET DEFAULT current_setting('app.firm_id', true)::int;
ALTER TABLE reconciliations    ALTER COLUMN firm_id SET DEFAULT current_setting('app.firm_id', true)::int;
ALTER TABLE invoices_company   ALTER COLUMN firm_id SET DEFAULT current_setting('app.firm_id', true)::int;
ALTER TABLE invoices_anaf      ALTER COLUMN firm_id SET DEFAULT current_setting('app.firm_id', true)::int;
ALTER TABLE differences        ALTER COLUMN firm_id SET DEFAULT current_setting('app.firm_id', true)::int;
ALTER TABLE audit_log          ALTER COLUMN firm_id SET DEFAULT current_setting('app.firm_id', true)::int;

-- ============ Row-Level Security pe cele 7 tabele per-firma ============
-- FORCE se aplica si proprietarului tabelei; politica citeste app.firm_id
-- (setat de adaptor la fiecare comutare de firma). WITH CHECK identic cu
-- USING: nu poti nici citi, nici scrie randurile altei firme.

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['clients','client_assignments','reconciliations',
                           'invoices_company','invoices_anaf','differences',
                           'audit_log'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS izolare_firma ON %I', t);
    EXECUTE format(
      'CREATE POLICY izolare_firma ON %I '
      'USING (firm_id = current_setting(''app.firm_id'', true)::int) '
      'WITH CHECK (firm_id = current_setting(''app.firm_id'', true)::int)', t);
  END LOOP;
END $$;

-- ============ drepturi pentru rolul aplicatiei ============
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO etva_app;
-- UPDATE (nu doar USAGE/SELECT) e obligatoriu pentru setval() - fara el,
-- migrarea datelor (portal/migrare_pg.py, pasul final de resetare a
-- secventelor peste MAX(id)) esueaza cu "permission denied for sequence"
-- desi INSERT-urile normale (care doar citesc secventa prin nextval,
-- acoperit de USAGE) merg perfect - descoperit printr-un test real, nu
-- teoretic, vezi tests/test_migrare_pg.py.
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO etva_app;
